### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by dalbertini** [stephenmkbrady/hexo-tag-html5#1]
Hello,
I need to install this plugin but the readme is too sort for me and i don't undestand.
I start with Hexo so can you help me ?
Best regards

edit : i install it with npm install hexo-tag-html5video but no work

**Comment by stephenmkbrady** [comment]
Hi dalbertini!

I've not used hexo in a while, but I was thinking of using again, I think hexo devs might have changed how plugins work.
You could try installing it with: https://github.com/adamsiwiec/hexagon It's a tool that manages themes and plugins. 

I just reread the plugin document and I think this plugin should still work and the hexagon tool might configure of files for the user to make it work, which is really nice to have. I'll try this weekend and post back here with updated better instructions or a fix if it's not working. 

Kind Regards,
Steve

**Comment by stephenmkbrady** [comment]
Hello again, 
I make a quick blog and added this tag with npm install hexo-tag-html5video and updated _config.yml with the new hexo-tag-html5video plugin. Added a video folder and linked to it and it seems to work. I updated the readme to walk through adding a video to your blog. Please have a read and if you get stuck on a step or if I wasn't clear in parts let me know and I'll update it again.

**Comment by dalbertini** [comment]
THX StephenBrady 🥇  : i will try again tomorrow (GMT+1 here)
nice job about readme 👍

**Comment by dalbertini** [comment]
Hello,
It 's working i find just now my error !!!!!
Before i was installed the plugin with npm outside my blog'directory so my plugins were outside my blog architecture. (I follow too excactly tutorial from Mike Dane: "hexo directory / web sites directories")
**THX A LOT stephenmkbrady**


edit : in fact **not working**
Front page is ok but when i click on title to open the blog'post the video desapear with MIME error
i don't know whats happen

**Comment by dalbertini** [comment]
**Help stephenmkbrady :'(** i cry a lot
Why the blog'post alone is not link correctly the video ? (and front page with all blog'posts are ok ?)

other note : the step 9 of your readme give me errors !!??

**Comment by stephenmkbrady** [comment]
Hi dalbertini,
Can you link me your hexo project? and then I can have a look and see what might be the problem.
Step 9 was a typo, thanks for testing the instructions, it should be "hexo server". I updated the instructions.

**Comment by dalbertini** [comment]
Hello and thx you for help me 👍 
Look here : http://dsll.fr/test_hexo/
the post on front page is ok because i read carrefully your readme BUT when click on Title (here a) to see only the post the video'link is lost so MIME error
best regards

**Comment by stephenmkbrady** [comment]
Ah I see now, ok, let me try that, I think I know why but I want to reproduce first to be sure.

**Comment by stephenmkbrady** [comment]
Hi dalbertini, 
To get the link to work in the post page and the front page, delete the following from your asset_path: "![]"
The ![] tell the router to use a relative path from the page, but for this we want an absolute path for the vid folder and it's contents so we don't use ![] in the asset_path.
Let me know if that fixes the issue

**Comment by dalbertini** [comment]
Hello Stephenmkbrady
Thx, but i don't understand what you write :
- i never use _**asset_path**_
- or i never use _**asset_path: "![]"**_
- i just copy the code from your readme like :
`{% html5video 50% 300px video/webm %}
vid/presentation_zi2.webm
{% endhtml5video %}`
- i don't have asset_path file inside my fresh website
- i just find **_post_asset_path: false_** inside the _**_config.yml**_ file


Sorry i am a big noob with hexo

**Comment by stephenmkbrady** [comment]
Hi dalbertini, 
Can you send me the site source code? I'll run it locally, and see why it's happening on your project.

**Comment by dalbertini** [comment]
Hello, i send you a link via your email of your account (sorry?) : hope you can help me
but it is a very fresh install of hexo + install of hexo-tag-html5 like your readme and also just install "next" theme
that's all

**Comment by stephenmkbrady** [comment]
Hi Dalbertini,
I was on a little holiday so I'm looking now.  I don't see an email regarding the project. 
Can you add it as a git repository to your github, and add me as a collaborator? 
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by dalbertini** [comment]
Hello StephenMKBrady
Happy to read you again :) and Happy to know you was on Holidays :)
First i find and I add my email on my account setting (was previously private ?!?) but i don't understand something you want be a collaborator but it s hard for a french guy like me to understand how to do !
Edit : i create a private repo and add you collaborator : do you think it s ok ?

**Comment by stephenmkbrady** [comment]
I updated the description, I forgot a forward slash on the file location so it should be good now.

**Comment by dalbertini** [comment]
Solved !
Thx Stephen for your help !
